---@class IDEFeatures
---@field telescope? boolean
---@field which_key? boolean
---@field treesitter? boolean
---@field lsp? boolean
---@field lualine? boolean
---@field refactoring? boolean
---@field dap? boolean

---@class IDEVimOptions
---@field expandtab? boolean
---@field shiftwidth? number
---@field tabstop? number
---@field softtabstop? number
---@field smartindent? boolean
---@field ignorecase? boolean
---@field smartcase? boolean
---@field cursorline? boolean
---@field cursorlineopt? string
---@field number? boolean
---@field numberwidth? number
---@field clipboard? string
---@field mouse? string
---@field timeoutlen? number
---@field fillchars? table
---@field whichwrap? string

---@class IDEConfig
---@field colorscheme? string|fun()
---@field options? IDEVimOptions
---@field keymaps? table
---@field features? IDEFeatures
