---@class IDEFeatures
---@field finder? boolean -- Fuzzy finding with Telescope
---@field keybind_help? boolean -- Keybinding help with Which-key
---@field syntax_highlighting? boolean -- Syntax highlighting with Treesitter
---@field lsp? boolean -- Language Server Protocol support
---@field statusline? boolean -- Enhanced statusline with Lualine
---@field refactoring? boolean -- Code refactoring tools
---@field debugging? boolean -- Debug Adapter Protocol (DAP) support

---@class IDEConfig
---@field colorscheme? string -- Default colorscheme (catppuccin)
---@field features? IDEFeatures -- Feature flags for enabling/disabling plugins
